import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useGlobalContext } from '../component/context';

export default function Home() {  
  const {setToken} = useGlobalContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>ULessons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div className={styles.btn_cntr}>
          <Link href="/home"><a><button className={styles.btn} onClick={setToken}>Start Test</button></a></Link>
          <Link href="/mockExam/allExams"><a><button className={styles.btn}>Mock Exam</button></a></Link>
        </div>
      </main>
    </div>
  )
}
