import Head from 'next/head';
import Router from 'next/router';

import styles from '../styles/Home.module.css';
import ExamComponent from '../component/ExamComponent';
import { useGlobalContext } from '../component/context';


export default function Home() {  
  const {allExams} = useGlobalContext();

  const redirectTo = () => {
    Router.push({
      pathname:'/myExams/upcoming'
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ULessons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className={styles.mockExam_cntr}>
        <div className={styles.mockexam_header}>
          {/* <MockExamHeaderComponent /> */}

          <div className={styles.first}>
            <div className={styles.icon}>
              <svg width="38" height="12" viewBox="0 0 38 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M6.11035 11.21L1.00035 6.32L6.11035 1" stroke="#313848" strokeWidth="1.5" strokeMiterlimit="10" strokeLinejoin="round"/>
                  <path d="M37.4697 6.1001H1.32973" stroke="#313848" strokeWidth="1.5" strokeMiterlimit="10" strokeLinejoin="round"/>
              </svg>
            </div>
            <span className={styles.heading}>Mock Exams</span> 
          </div>

          <div className={styles.second} onClick={redirectTo}>
            <div className={styles.secondChild}>
              <svg width="21" height="21" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clipPath="url(#clip0_274_1332)">
                <path d="M3.48116 0.397949C2.56606 0.397949 1.82422 1.13978 1.82422 2.05489V18.6242C1.82422 19.5393 2.56605 20.2812 3.48116 20.2812H16.7366C17.6517 20.2812 18.3936 19.5393 18.3936 18.6242V4.47799L18.2067 4.29596L14.2237 0.397949H3.48116ZM3.06692 2.46912C3.06692 2.01157 3.43784 1.64065 3.89539 1.64065H13.4228V5.35905H17.1509V18.21C17.1509 18.6676 16.78 19.0385 16.3224 19.0385H3.89539C3.43784 19.0385 3.06692 18.6676 3.06692 18.21V2.46912ZM14.6655 2.57025L16.2456 4.11635H14.6655V2.57025ZM4.93097 7.85416C4.58781 7.85416 4.30962 8.13235 4.30962 8.47551V8.47551C4.30962 8.81868 4.58781 9.09686 4.93097 9.09686V9.09686C5.27414 9.09686 5.55233 8.81868 5.55233 8.47551V8.47551C5.55233 8.13235 5.27414 7.85416 4.93097 7.85416V7.85416ZM7.41638 7.85416C7.07322 7.85416 6.79503 8.13235 6.79503 8.47551V8.47551C6.79503 8.81868 7.07322 9.09686 7.41638 9.09686H15.2868C15.63 9.09686 15.9082 8.81868 15.9082 8.47551V8.47551C15.9082 8.13235 15.63 7.85416 15.2868 7.85416H7.41638ZM4.93097 11.5823C4.58781 11.5823 4.30962 11.8605 4.30962 12.2036V12.2036C4.30962 12.5468 4.58781 12.825 4.93097 12.825V12.825C5.27414 12.825 5.55233 12.5468 5.55233 12.2036V12.2036C5.55233 11.8605 5.27414 11.5823 4.93097 11.5823V11.5823ZM7.41638 11.5823C7.07322 11.5823 6.79503 11.8605 6.79503 12.2036V12.2036C6.79503 12.5468 7.07322 12.825 7.41638 12.825H15.2868C15.63 12.825 15.9082 12.5468 15.9082 12.2036V12.2036C15.9082 11.8605 15.63 11.5823 15.2868 11.5823H7.41638ZM4.93097 15.3104C4.58781 15.3104 4.30962 15.5886 4.30962 15.9317V15.9317C4.30962 16.2749 4.58781 16.5531 4.93097 16.5531V16.5531C5.27414 16.5531 5.55233 16.2749 5.55233 15.9317V15.9317C5.55233 15.5886 5.27414 15.3104 4.93097 15.3104V15.3104ZM7.41638 15.3104C7.07322 15.3104 6.79503 15.5886 6.79503 15.9317V15.9317C6.79503 16.2749 7.07322 16.5531 7.41638 16.5531H15.2868C15.63 16.5531 15.9082 16.2749 15.9082 15.9317V15.9317C15.9082 15.5886 15.63 15.3104 15.2868 15.3104H7.41638Z" fill="white"/>
                </g>
                <defs>
                <clipPath id="clip0_274_1332">
                <rect width="19.8832" height="19.8832" fill="white" transform="translate(0.996094 0.397949)"/>
                </clipPath>
                </defs>
              </svg>

              {/* <Link href="/myExams"><a><button className={styles.myExamButton}>My Exams</button></a></Link> */}
              <button className={styles.myExamButton} >My Exams</button>
            </div>
          </div>
        </div>

        <div className={styles.mockexam_body}>
          <div className={styles.image_cntr}>
            {/* <Image src={image} layout='responsive' height="144px"  /> */}
          </div>
          <div className={styles.exam_component_list}>
            {allExams.map((exam) => {
                return(
                  <div key={exam._id}><ExamComponent examObj={exam} /></div>
                )
            })}
          </div>
        </div>
      </div>
    </div>
  )
}
