import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {  
  return (
    <div className={styles.container}>
      <Head>
        <title>ULessons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <Link href="/home"><a><button className={styles.btn}>Start Test</button></a></Link>
      </main>
    </div>
  )
}
